In [32]:
'''
A1 Please refer to the “Purchase Data” worksheet of Lab Session Data.xlsx. Please load the data
and segregate them into 2 matrices A & C (following the nomenclature of AX = C). Do the following
activities.

A2. Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products
available with the vendor.

A3. Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others
as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on
purchase behavior.
'''

import pandas as pd
import numpy as np
df = pd.read_csv('purchase.csv')

print(df.to_string()) 
A = df[['Candies (#)','Mangoes (Kg)','Milk Packets (#)']]
dim=df.to_numpy().shape
print("dimentionality of dataset is:",dim)
print("number of vectors is :",dim[0])
matA = A.values
C= df['Payment (Rs)']
matC=C.values
print("Matrix A:\n", matA)
rank = np.linalg.matrix_rank(matA)
print("rank of matrix A is ", rank)
print("Matrix C:\n", matC)
invA=np.linalg.pinv(matA)
print("Inverse of A:\n", invA)
res = np.dot(invA,matC)
print("Matrix X:\n",res)

df['RICH/POOR'] = df['Payment (Rs)'].apply(lambda x: 'RICH' if x > 200 else 'POOR')
print(df.to_string())

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
dimentionality of dataset is: (10, 5)
number of vectors is : 10
Matrix A:
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
rank of matrix A is  3
Matrix C:
 

In [37]:
irctcDF = pd.read_csv('IRCTC.csv')
print(irctcDF)
print(irctcDF["Price"].mean())

             Date Month  Day     Price      Open      High       Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2,081.85  2,092.00  2,126.90  2,065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2,077.75  2,084.00  2,112.45  2,068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2,068.85  2,084.35  2,088.50  2,053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2,072.95  2,098.00  2,098.00  2,066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2,078.25  2,102.00  2,111.40  2,072.00  809.62K   
..            ...   ...  ...       ...       ...       ...       ...      ...   
244  Jul 07, 2020   Jul  Tue  1,397.40  1,410.00  1,411.00  1,390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1,400.75  1,405.50  1,415.50  1,394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1,405.10  1,415.00  1,425.00  1,398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1,412.35  1,440.00  1,467.80  1,395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1,363.05  1,363.65  1,377.00  1,356.00  383.00K   

       Chg%  
0     0.20%  

TypeError: Could not convert string '2,081.852,077.752,068.852,072.952,078.252,083.002,076.852,011.702,050.402,089.952,097.952,064.402,106.352,093.752,071.202,144.852,094.801,921.701,921.801,917.951,894.601,903.201,896.251,928.351,894.051,907.951,884.501,862.001,855.651,858.101,835.051,762.101,747.651,746.601,792.301,748.651,693.401,725.201,723.651,770.201,765.551,791.401,792.551,795.851,793.201,730.851,712.001,673.051,640.051,612.701,627.451,608.101,611.651,582.001,730.901,726.401,709.001,688.551,702.651,751.751,757.001,755.251,747.401,721.851,760.551,842.151,838.051,855.451,766.651,824.001,904.051,947.051,987.352,018.502,026.702,015.451,940.851,961.101,886.101,897.651,938.451,759.651,726.951,675.451,632.901,615.851,675.401,701.201,698.651,674.151,713.101,731.901,619.001,618.401,641.751,618.701,555.001,518.901,469.351,470.501,459.901,456.101,457.051,438.251,426.251,432.451,454.501,452.701,443.501,423.351,441.201,463.101,461.151,480.451,460.701,471.501,489.451,483.451,456.851,451.051,445.001,437.801,434.951,410.801,417.951,408.951,411.551,399.051,373.501,424.501,424.851,423.401,441.001,479.001,421.001,452.751,617.751,648.501,691.551,570.601,378.051,349.901,358.101,353.451,351.351,353.901,362.301,362.351,381.151,376.051,365.301,380.301,389.251,381.451,371.251,374.351,312.851,311.201,310.401,300.551,301.451,302.251,315.201,330.601,333.351,326.001,320.651,327.951,327.751,331.751,332.201,326.901,328.101,329.501,338.051,336.501,334.651,351.001,355.601,356.901,363.851,376.051,379.301,384.001,383.351,367.051,352.051,338.851,372.851,355.701,397.351,405.351,370.701,367.401,369.801,367.851,370.551,370.851,348.901,379.451,414.851,365.201,368.701,359.751,351.501,344.251,366.501,367.501,369.301,341.751,338.101,341.801,347.051,361.801,377.651,383.551,368.601,384.101,386.801,372.051,323.751,331.351,334.551,336.951,339.801,339.701,335.851,340.701,352.751,345.551,344.851,357.851,371.501,372.951,390.201,376.451,370.951,364.201,351.951,362.151,397.351,400.951,385.051,390.101,397.401,400.751,405.101,412.351,363.05' to numeric